kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "kyverno.fullname" . }}
  namespace: {{ template "kyverno.namespace" . }}
  labels:
    {{ include "kyverno.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{ include "kyverno.matchLabels" . | nindent 6 }}
  egress:
  - {}
  ingress:
  - ports:
    - port: 443
      protocol: TCP
    - port: 9443
      protocol: TCP
  policyTypes:
  - Egress
  - Ingress
