{{- if not (lookup "v1" "Namespace" "" "policy-exceptions")}}
apiVersion: v1
kind: Namespace
metadata:
  name: policy-exceptions
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "labels.common" . | nindent 4 }}
{{- end }}
