{{- if .Values.metricsService.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kyverno.fullname" . }}
  labels: {{ include "kyverno.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kyverno.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: monitoring
    interval: {{ .Values.metrics.scrapeInterval }}
{{- end }}
