{{- if .Values.crds.install }}
{{- if not .Values.global.podSecurityStandards.enforced }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "kyverno-stack.crdInstall" . }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-6"
    {{- include "kyverno-stack.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "kyverno-stack.crdInstall" . | quote }}
    {{- include "kyverno-stack.selectorLabels" . | nindent 4 }}
    role: {{ include "kyverno-stack.CRDInstallSelector" . | quote }}
spec:
  privileged: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  volumes:
  - 'configMap'
  hostPID: false
  hostIPC: false
  hostNetwork: false
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
{{- end }}
{{- end }}
