{{/*
We have to create individual jobs for each CRD - they timeout during installation
*/}}
{{ $currentScope := . }}
{{- if .Values.crds.install }}
  {{- range $path, $_ := .Files.Glob "crd/**" }}
    {{- with $currentScope }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kyverno-stack.crdInstall" . }}-{{ $path | base | trimSuffix ".yaml" }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-1"
    {{- include "kyverno-stack.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "kyverno-stack.crdInstall" . | quote }}
    {{- include "kyverno-stack.selectorLabels" . | nindent 4 }}
    role: {{ include "kyverno-stack.CRDInstallSelector" . | quote }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "kyverno-stack.crdInstall" . | quote }}
        {{- include "kyverno-stack.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kyverno-stack.crdInstall" . }}
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: kubectl
        image: "{{ .Values.image.registry }}/giantswarm/docker-kubectl:latest"
        command:
        - sh
        - -c
        - |
          set -o errexit ; set -o xtrace ; set -o nounset

          # piping stderr to stdout means kubectl's errors are surfaced
          # in the pod's logs.
          kubectl apply -f /data/ 2>&1
        volumeMounts:
        - name: {{ $path | base | trimSuffix ".yaml" }}
          mountPath: /data/{{ $path | base }}
          subPath: {{ $path | base }}
        resources: {{- toYaml .Values.crds.resources | nindent 10 }}
      volumes:
      - name: {{ $path | base | trimSuffix ".yaml" }}
        configMap:
          name: {{ include "kyverno-stack.crdInstall" . }}-{{ $path | base | trimSuffix ".yaml" }}
          items:
          - key: content
            path: {{ $path | base }}
      restartPolicy: Never
  backoffLimit: 4
    {{- end }}
  {{- end }}
{{- end }}
