apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm/kyverno/charts/kyverno
  contents:
  - path: .
    git:
      url: https://github.com/kyverno/kyverno
      # renovate: datasource=github-tags depName=kyverno/kyverno
      ref: v1.17.0
    includePaths:
      - charts/kyverno/**
    excludePaths:
      - charts/kyverno/charts/crds/**
    newRootPath: charts/kyverno
- path: helm/kyverno/charts/policy-reporter
  contents:
  - path: .
    git:
      url: https://github.com/kyverno/policy-reporter
      # renovate: datasource=github-tags depName=kyverno/policy-reporter
      ref: v3.7.0
    includePaths:
      - charts/policy-reporter/**
    newRootPath: charts/policy-reporter

