apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm/kyverno/charts/kyverno
  contents:
  - path: .
    git:
      url: https://github.com/giantswarm/kyverno-upstream
      ref: v1.12.5
    includePaths:
      - charts/kyverno/**
    newRootPath: charts/kyverno
- path: helm/kyverno/charts/policy-reporter
  contents:
  - path: .
    git:
      url: https://github.com/giantswarm/policy-reporter-upstream
      ref: v2.17.5
    includePaths:
      - charts/policy-reporter/**
    newRootPath: charts/policy-reporter

