apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kyvernoplugin.fullname" . }}-config
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kyvernoplugin.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ tpl (.Files.Get "config.yaml") . | b64enc }}
