{{- if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ template "kyverno-stack.fullname" . }}
  labels:
    {{- include "kyverno-stack.labels" . | nindent 4 }}
  namespace: {{ include "kyverno-stack.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "kyverno-stack.selectorLabels" . | nindent 6 }}
  egress:
    - toEntities:
        - kube-apiserver
  ingress:
    - fromEntities:
        - kube-apiserver
        - cluster
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-kyverno-admission-controller-talk-to-apiserver
  namespace: {{ include "kyverno-stack.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: admission-controller
      app.kubernetes.io/instance: kyverno
  egress:
    - toEntities:
      - kube-apiserver
      toPorts:
        - ports:
          - port: "443"
            protocol: TCP
          - port: "6443"
            protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-kyverno-plugin-talk-to-apiserver
  namespace: {{ include "kyverno-stack.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: kyverno-plugin
      app.kubernetes.io/instance: kyverno
  egress:
    - toEntities:
      - kube-apiserver
      toPorts:
        - ports:
          - port: "443"
            protocol: TCP
          - port: "6443"
            protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-kyverno-policy-reporter-talk-to-apiserver
  namespace: {{ include "kyverno-stack.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: policy-reporter
      app.kubernetes.io/instance: kyverno
  egress:
    - toEntities:
      - kube-apiserver
      toPorts:
        - ports:
          - port: "443"
            protocol: TCP
          - port: "6443"
            protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-kyverno-background-controller-talk-to-apiserver
  namespace: {{ include "kyverno-stack.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: background-controller
      app.kubernetes.io/instance: kyverno
  egress:
    - toEntities:
      - kube-apiserver
      toPorts:
        - ports:
          - port: "443"
            protocol: TCP
          - port: "6443"
            protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-kyverno-reports-controller-talk-to-apiserver
  namespace: {{ include "kyverno-stack.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: reports-controller
      app.kubernetes.io/instance: kyverno
  egress:
    - toEntities:
      - kube-apiserver
      toPorts:
        - ports:
          - port: "443"
            protocol: TCP
          - port: "6443"
            protocol: TCP
{{- end }}
