{{- if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ template "kyverno-stack.fullname" . }}
  labels:
    {{- include "kyverno-stack.labels" . | nindent 4 }}
  namespace: {{ include "kyverno-stack.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "kyverno-stack.selectorLabels" . | nindent 6 }}
  egress:
    - toEntities:
        - kube-apiserver
  ingress:
    - fromEntities:
        - kube-apiserver
        - cluster
{{- end }}
