{{- if and .Values.kyverno.upgrade.fromV2 .Values.upgradeJob.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kyverno-stack.upgradeJob.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "kyverno-stack.upgradeJob.name" . | quote }}
    {{- include "kyverno-stack.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "-5"
    {{- include "kyverno-stack.upgradeJob.annotations" . | nindent 4 }}
{{- end }}
