{{ if ".Values.policy-reporter.psp.enabled" }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "kyverno-stack.fullname" . }}-polr-psp
  labels:
    {{- include "kyverno-stack.labels" . | nindent 4 }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
spec:
  privileged: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  runAsUser:
    rule: MustRunAsNonRoot
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - 'secret'
    - 'configMap'
    - 'emptyDir'
  allowPrivilegeEscalation: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kyverno-stack.fullname" . }}-polr-psp
  labels:
    {{- include "kyverno-stack.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ template "kyverno-stack.fullname" . }}-polr-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kyverno-stack.fullname" . }}-polr-psp
  labels:
    {{- include "kyverno-stack.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ index .Values "policy-reporter" "serviceAccount" "name" }}
    namespace: {{ include "kyverno-stack.namespace"  . }}
roleRef:
  kind: ClusterRole
  name: {{ template "kyverno-stack.fullname" . }}-polr-psp
  apiGroup: rbac.authorization.k8s.io
{{- end }}