project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

# We install CRDs through a Job with the helm specific crd folder.
crds:
  install: true

image:
  registry: quay.io

# Additional options defined in charts/kyverno/values.yaml. Upstream docs: https://github.com/kyverno/kyverno
kyverno:
  # We do not want Kyverno to install these CRDs.
  # Kyverno managed them through helm templates which clashes with chart-operator.
  installCRDs: false
  fullnameOverride: kyverno
  image:
    repository: quay.io/giantswarm/kyverno
    tag: v1.5.1
    pullPolicy: IfNotPresent
  initImage:
    repository: quay.io/giantswarm/kyvernopre
    tag: v1.5.1
  replicaCount: 3
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 256Mi
  initResources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
  metricsService:
    create: true
    type: ClusterIP
    port: 8000
  podDisruptionBudget:
    enabled: false
    maxUnavailable:
    minAvailable:

# Additional options defined in charts/policy-reporter/values.yaml. Upstream docs: https://github.com/kyverno/policy-reporter
policy-reporter:
  image:
    registry: quay.io
    repository: giantswarm/policy-reporter
  resources:
    limits:
      cpu: 15m
      memory: 100Mi
    requests:
      cpu: 5m
      memory: 30Mi

  ui:
    enabled: true
    image:
      registry: quay.io
      repository: giantswarm/policy-reporter-ui
    plugins:
      kyverno: true
    resources:
      limits:
        cpu: 10m
        memory: 16Mi
      requests:
        cpu: 1m
        memory: 8Mi

  kyvernoPlugin:
    enabled: true
    image:
      registry: quay.io
      repository: giantswarm/policy-reporter-kyverno-plugin
    resources:
      limits:
        cpu: 10m
        memory: 30Mi
      requests:
        cpu: 1m
        memory: 15Mi

  global:
    plugins:
      kyverno: true

  monitoring:
    enabled: false
    namespace: monitoring
