project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

crds:
  install: true

image:
  registry: quay.io

kyverno:
  installCRDs: false
  fullnameOverride: kyverno
  image:
    repository: quay.io/giantswarm/kyverno
    # Defaults to appVersion in Chart.yaml if omitted
    tag: v1.5.0
    pullPolicy: IfNotPresent
  initImage:
    repository: quay.io/giantswarm/kyvernopre
    tag: v1.5.0
  replicaCount: 3
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 256Mi
  initResources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
  metricsService:
    create: true
    type: ClusterIP
    ## Kyverno's metrics server will be exposed at this port
    port: 8000


# Additional options defined in charts/policy-reporter/values.yaml. Upstream docs: https://github.com/kyverno/policy-reporter
policy-reporter:
  image:
    repository: quay.io/giantswarm/policy-reporter
    tag: 1.10.1
  resources:
    limits:
      cpu: 15m
      memory: 50Mi
    requests:
      cpu: 5m
      memory: 30Mi

  ui:
    enabled: true
    image:
      repository: quay.io/giantswarm/policy-reporter-ui
      tag: 0.15.0
    plugins:
      kyverno: true
    resources:
      limits:
        cpu: 10m
        memory: 16Mi
      requests:
        cpu: 1m
        memory: 8Mi

  kyvernoPlugin:
    enabled: true
    image:
      repository: quay.io/giantswarm/policy-reporter-kyverno-plugin
      tag: 0.3.2
    resources:
      limits:
        cpu: 10m
        memory: 30Mi
      requests:
        cpu: 1m
        memory: 15Mi

  global:
    plugins:
      kyverno: true

  monitoring:
    enabled: true
    namespace: monitoring
