# We install CRDs through a Job with the helm specific crd folder.
crds:
  install: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 750m
      memory: 1024Mi

image:
  registry: docker.io

verticalPodAutoscaler:
  kyvernoPlugin:
    enabled: true
    containerPolicies: {}
  policyReporter:
    enabled: true
    containerPolicies: {}
  ui:
    enabled: true
    containerPolicies: {}

policyExceptions:
  # Kyverno will accept PolicyExceptions from all namespaces.
  # If enablePolexPolicy is true, this chart will deploy an additional
  # ClusterPolicy which rejects PolicyException objects created outside
  # of the namespaces listed in allowedPolexNamespaces.
  enablePolexPolicy: true
  allowedPolexNamespaces:
  - monitoring
  # For security reasons, we don't disclose the allowed namespaces when a polex is rejected.
  # The message shown to users can be customized to direct them to an exception process.
  polexPolicyMessage: >-
    PolicyExceptions are not allowed to be created in the {{ request.namespace }} namespace.
    Pleaes contact a cluster administrator for assistance.

# Additional options defined in charts/kyverno/values.yaml. Upstream docs: https://github.com/kyverno/kyverno
kyverno:
  service:
    annotations: {}
  # Labels on the Deployment. See podLabels for Pod-level labels.
  customLabels:
    giantswarm.io/service-type: "managed"
    giantswarm.io/monitoring_basic_sli: "true"
    application.giantswarm.io/team: "shield"

  # We do not want Kyverno to install these CRDs.
  # Kyverno managed them through helm templates which clashes with chart-operator.
  installCRDs: false
  fullnameOverride: kyverno
  image:
    registry: docker.io
    repository: giantswarm/kyverno
    pullPolicy: IfNotPresent
  initImage:
    registry: docker.io
    repository: giantswarm/kyvernopre
  replicaCount: 3
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 256Mi
  initResources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
  metricsService:
    create: true
    type: ClusterIP
    port: 8000
    annotations:
      giantswarm.io/monitoring-port: "8000"
      giantswarm.io/monitoring-app-label: "kyverno"
      giantswarm.io/monitoring: "true"
  podDisruptionBudget:
    maxUnavailable: 1
    minAvailable: ""
  priorityClassName: "giantswarm-critical"
  # -- Exclude Kyverno namespace
  # Determines if default Kyverno namespace exclusion is enabled for webhooks and resourceFilters
  excludeKyvernoNamespace: true
  config:
    webhooks:
      - namespaceSelector:
          matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: NotIn
            values:
              - kube-system
  psp:
    enabled: true
  rbac:
    serviceAccount:
      name: "kyverno"  # Added so that we can create a PSP allowing emptyDir and seccomp profiles. Can be removed when PSPs are removed.
  extraArgs:
    - --enablePolicyException=true
    - --loggingFormat=text

  cleanupController:
    # -- Enable cleanup controller.
    enabled: false

    rbac:
      # -- Create RBAC resources
      create: true

      serviceAccount:
        # -- Service account name
        name:

      clusterRole:
        # -- Extra resource permissions to add in the cluster role
        extraResources: []
        # - apiGroups:
        #     - ''
        #   resources:
        #     - pods

    # -- Create self-signed certificates at deployment time.
    # The certificates won't be automatically renewed if this is set to `true`.
    createSelfSignedCert: false

    image:
      registry: docker.io
      repository: giantswarm/cleanup-controller  # kyverno: replaced in e2e tests
      pullPolicy: IfNotPresent

# Additional options defined in charts/policy-reporter/values.yaml. Upstream docs: https://github.com/kyverno/policy-reporter
policy-reporter:
  image:
    registry: docker.io
    repository: giantswarm/policy-reporter
  resources:
    limits:
      cpu: 30m
      memory: 100Mi
    requests:
      cpu: 5m
      memory: 30Mi
  serviceAccount:
    name: "policyreporter-sa"  # Only needed to support adding a PSP. Can be removed when PSPs are disabled.

  ui:
    enabled: true
    image:
      registry: docker.io
      repository: giantswarm/policy-reporter-ui
    plugins:
      kyverno: true
    resources:
      limits:
        cpu: 10m
        memory: 16Mi
      requests:
        cpu: 1m
        memory: 8Mi
    serviceAccount:
      create: true
      name: "policyreporter-ui-sa"  # Only needed to support adding a PSP. Can be removed when PSPs are disabled.

  kyvernoPlugin:
    enabled: true
    annotations:
      giantswarm.io/monitoring: "true"
    image:
      registry: docker.io
      repository: giantswarm/policy-reporter-kyverno-plugin
    resources:
      limits:
        cpu: 50m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 30Mi
    serviceAccount:
      name: "policyreporter-plugin-sa"  # Only needed to support adding a PSP. Can be removed when PSPs are disabled.

  global:
    plugins:
      kyverno: true

    labels: {}

  monitoring:
    enabled: false
    namespace: monitoring

  # Create a PSP and ClusterRoleBinding for PolicyReporter.
  psp:
    enabled: true
