{{ if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  namespace: {{ include "policyreporter.namespace" . }}
  name: {{ include "policyreporter.fullname" . }}
  labels:
    {{- include "policyreporter.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "policyreporter.selectorLabels" . | nindent 6 }}
  egress:
    # To scrape the vault token expiration
    - toEntities:
        - kube-apiserver
{{ end }}
