{{- with (.Values.monitoring).podLogs }}
{{- if and .enabled (not $.Values.kyverno.templating.debug) }}
apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  name: {{ include "kyverno.admission-controller.name" $.Subcharts.kyverno }}
  namespace: {{ include "kyverno.namespace" $.Subcharts.kyverno }}
  labels:
    {{- include "kyverno.admission-controller.labels" $.Subcharts.kyverno | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: {{ include "kyverno.namespace" $.Subcharts.kyverno }}
  selector:
    matchLabels:
      {{- include "kyverno.admission-controller.matchLabels" $.Subcharts.kyverno | nindent 6 }}
  relabelings:
  - action: replace
    replacement: {{ .tenant }}
    targetLabel: giantswarm_observability_tenant
  {{- with .relabelings }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
