{{- if .Values.verticalPodAutoscaler.policyReporter.enabled -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "kyverno-stack.fullname" . }}-policyreporter-vpa
  namespace: {{ include "kyverno-stack.namespace" . }}
  labels:
    {{- include "kyverno-stack.labels" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
    {{- if .Values.verticalPodAutoscaler.policyReporter.containerPolicies }}
      {{- with .Values.verticalPodAutoscaler.policyReporter.containerPolicies -}}
        {{ tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
    {{- end }}
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       {{ include "kyverno-stack.fullname" . }}-policy-reporter
  updatePolicy:
    updateMode: Auto
{{- end -}}
