{{- if .Values.policyExceptions.enableAwsCloudControllerManagerPolex }}
apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: kyverno-app-aws-cloud-controller-policy-exception
  namespace: giantswarm
  labels:
    {{- include "kyverno-stack.labels" . | nindent 4 }}
spec:
  exceptions:
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root
    - autogen-run-as-non-root
  - policyName: restrict-seccomp-strict
    ruleNames:
    - check-seccomp-strict
    - autogen-check-seccomp-strict
  - policyName: disallow-capabilities-strict
    ruleNames:
    - adding-capabilities-strict
    - autogen-adding-capabilities-strict
    - require-drop-all
    - autogen-require-drop-all
  - policyName: disallow-host-namespaces
    ruleNames:
    - host-namespaces
    - autogen-host-namespaces
  - policyName: require-run-as-non-root-user
    ruleNames:
    - run-as-non-root-user
    - autogen-run-as-non-root-user
  match:
    any:
    - resources:
        kinds:
        - DaemonSet
        - ReplicaSet
        - Pod
        namespaces:
        - kube-system
        names:
        - aws-cloud-controller-manager*
{{- end }}
