{{- if .Values.policyExceptions.enableAwsEbsCsiDriverPolex }}
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: kyverno-app-aws-ebs-csi-driver-policy-exception 
  namespace: giantswarm
  labels:
    {{- include "kyverno-stack.labels" . | nindent 4 }}
  annotations:
    {{- include "kyverno-stack.policyInstallAnnotations" . | nindent 4 }}
spec:
  exceptions:
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
  - policyName: restrict-volume-types
    ruleNames:
    - restricted-volumes
    - autogen-restricted-volumes
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root 
    - autogen-run-as-non-root
  - policyName: restrict-seccomp-strict
    ruleNames:
    - check-seccomp-strict
    - autogen-check-seccomp-strict
  - policyName: disallow-capabilities-strict
    ruleNames:
    - adding-capabilities-strict
    - autogen-adding-capabilities-strict
    - require-drop-all
    - autogen-require-drop-all
  - policyName: disallow-privilege-escalation
    ruleNames:
    - privilege-escalation
    - autogen-privilege-escalation
  - policyName: require-run-as-non-root-user
    ruleNames:
    - run-as-non-root-user
    - autogen-run-as-non-root-user
  - policyName: disallow-privileged-containers
    ruleNames:
    - privileged-containers
    - autogen-privileged-containers
  match:
    any:
    - resources:
        kinds:
        - DaemonSet
        - Deployment
        - ReplicaSet
        - Pod
        namespaces:
        - kube-system
        names:
        - ebs-csi*
{{- end }}
