{{- if .Values.policyExceptions.enableAwsEbsCsiDriverPolex }}
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: kyverno-app-azure-scheduled-events-policy-exception 
  namespace: giantswarm
  labels:
    {{- include "kyverno-stack.labels" . | nindent 4 }}
  annotations:
    {{- include "kyverno-stack.policyInstallAnnotations" . | nindent 4 }}
spec:
  exceptions:
  - policyName: require-run-as-nonroot
    ruleNames:
    - run-as-non-root 
    - autogen-run-as-non-root
  - policyName: disallow-capabilities-strict
    ruleNames:
    - adding-capabilities-strict
    - autogen-adding-capabilities-strict
    - require-drop-all
    - autogen-require-drop-all
  - policyName: disallow-privilege-escalation
    ruleNames:
    - privilege-escalation
    - autogen-privilege-escalation
  match:
    any:
    - resources:
        kinds:
        - DaemonSet
        - Pod
        namespaces:
        - kube-system
        names:
        - azure-scheduled-events*
{{- end }}
