{{- if .Values.policyExceptions.enableCertExporterPolex }}
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: kyverno-app-cert-exporter-policy-exception
  namespace: giantswarm
  labels:
    {{- include "kyverno-stack.labels" . | nindent 4 }}
  annotations:
    {{- include "kyverno-stack.policyInstallAnnotations" . | nindent 4 }}
spec:
  exceptions:
  - policyName: disallow-host-ports
    ruleNames:
    - host-ports-none
    - autogen-host-ports-none
  - policyName: disallow-host-namespaces
    ruleNames:
    - host-namespaces
    - autogen-host-namespaces
  - policyName: disallow-privilege-escalation
    ruleNames:
    - autogen-privilege-escalation
  - policyName: restrict-seccomp-strict
    ruleNames:
    - autogen-check-seccomp-strict
  - policyName: disallow-capabilities-strict
    ruleNames:
    - autogen-require-drop-all

  match:
    any:
    - resources:
        kinds:
        - DaemonSet
        - Deployment
        - ReplicaSet
        - Pod
        namespaces:
        - giantswarm
        - monitoring
        names:
        - cert-exporter*
{{- end -}}
