{{- if .Values.policyExceptions.enableChartOperatorPolex }}
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: kyverno-app-chart-operator-policy-exception
  namespace: giantswarm
  labels:
    {{- include "kyverno-stack.labels" . | nindent 4 }}
  annotations:
    {{- include "kyverno-stack.policyInstallAnnotations" . | nindent 4 }}
spec:
  exceptions:
  - policyName: disallow-host-ports
    ruleNames:
    - host-ports-none
    - autogen-host-ports-none
  - policyName: disallow-host-namespaces
    ruleNames:
    - host-namespaces
    - autogen-host-namespaces

  match:
    any:
    - resources:
        kinds:
        - Deployment
        - ReplicaSet
        - Pod
        namespaces:
        - giantswarm
        names:
        - chart-operator*
{{- end -}}
