{{- if .Values.policyExceptions.enableK8sAuditMetrics }}
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: kyverno-app-k8s-audit-metrics-policy-exception
  namespace: giantswarm
  labels:
    {{- include "kyverno-stack.labels" . | nindent 4 }}
  annotations:
    {{- include "kyverno-stack.policyInstallAnnotations" . | nindent 4 }}
spec:
  exceptions:
  - policyName: disallow-capabilities-strict 
    ruleNames:
    - require-drop-all 
    - autogen-require-drop-all
  - policyName: disallow-privilege-escalation
    ruleNames:
    - privilege-escalation 
    - autogen-privilege-escalation
  - policyName: require-run-as-non-root-user
    ruleNames:
    - run-as-non-root-user 
    - autogen-run-as-non-root-user
  - policyName: require-run-as-nonroot 
    ruleNames:
    - run-as-non-root 
    - autogen-run-as-non-root

  match:
    any:
    - resources:
        kinds:
        - DaemonSet
        - Pod
        namespaces:
        - kube-system 
        - giantswarm
        - monitoring
        names:
        - k8s-audit-metrics*
{{- end -}}
