name: Sync from fork

on:
  push: # For testing
  schedule:
    - cron: '0 8 */7 * *' # At 08:00 on every 7th day-of-month

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  policy_reporter_fork_repo: https://github.com/giantswarm/policy-reporter-upstream
  kyverno_fork_repo: https://github.com/giantswarm/kyverno-upstream
  branch: 'main#update-chart'

jobs:
  # sync-app-kyverno-with-fork:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - run: |
  #         # Get the last tag from fork repo
  #         POLICY_REPORTER_LAST_TAG=$(git ls-remote --tags --sort='v:refname' --refs $policy_reporter_fork_repo \
  #          | tail -1 | cut -d '/' -f3)
  #         echo "Policy Reporter last tag found is $POLICY_REPORTER_LAST_TAG"

  #         KYVERNO_LAST_TAG=$(git ls-remote --tags --sort='v:refname' --refs $kyverno_fork_repo \
  #          | tail -1 | cut -d '/' -f3)
  #         echo "Kyverno last tag found is $KYVERNO_LAST_TAG"

  #         # Setup git config
  #         git config user.name github-actions
  #         git config user.email github-actions@github.com
          
  #         git checkout -b $branch

  #         # Modify the version in Vendir config
  #         sed -i "/policy-reporter/{n;s/ref: .*/ref: $POLICY_REPORTER_LAST_TAG/}" vendir.yml
  #         sed -i "/kyverno/{n;s/ref: .*/ref: $KYVERNO_LAST_TAG/}" vendir.yml
  #         git add vendir.yml
  #         git commit -m "Update app version from fork repo"
  #         git push origin $branch
  # call-update-chart:
  #   uses: ./.github/workflows/zz_generated.update_chart.yaml
  #   needs: sync-app-kyverno-with-fork
  #   with:
  #     branch: 'main#update-chart'
  copy-kyverno-crds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main#update-chart'
      - name: Remove previous CRDs and install new ones
        run: |
          cd kyverno-app/helm/kyverno

          # Remove previous CRDs
          git rm -f crd/*
          
          # Move new CRDs to crd directory
          mv charts/kyverno/templates/crds.yaml crd/

          # Split CRDs into multiple files
          cd crd
          yq -s '"crd-" + $index + ".yaml"' crds.yaml

          # Remove original file
          rm -f crds.yaml

          # Setup git config
          git config user.name github-actions
          git config user.email github-actions@github.com

          # Commit and push
          git add .
          git commit -m "Update CRDs"
          git push origin 'main#update-chart'
