name: Sync from fork

on:
  push:
    branches:
      - 'main' # Run at every sync
      - 'test-automation' # For testing
  schedule:
    - cron: '0 7 */7 * *' # At 07:00 on every 7th day-of-month

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-app-kyverno-with-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          # Get the last tag from fork repo
          POLICY_REPORTER_LAST_TAG=$(git ls-remote --tags --sort='v:refname' --refs https://github.com/giantswarm/policy-reporter \
           | tail -1 | cut -d '/' -f3)
          echo "Policy Reporter last tag found is $POLICY_REPORTER_LAST_TAG"

          KYVERNO_LAST_TAG=$(git ls-remote --tags --sort='v:refname' --refs https://github.com/giantswarm/kyverno \
           | tail -1 | cut -d '/' -f3)
          echo "Policy Reporter last tag found is $KYVERNO_LAST_TAG"

          # Setup git config
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b 'main#update-chart'

          # Modify the version in Vendir config
          sed -i "/policy-reporter/{n;s/ref: .*/ref: $POLICY_REPORTER_LAST_TAG/}" vendir.yml
          sed -i "/kyverno/{n;s/ref: .*/ref: $KYVERNO_LAST_TAG/}" vendir.yml
          # sed -i -r "s/(ref:).*/\1 $LAST_TAG/g" vendir.yml
          git add vendir.yml
          git commit -m "Update app version from fork repo"
          git push origin 'main#update-chart'
